[package]
name = "perfectly_sperical_houses_in_a_vacuum"
version = "0.1.0"
authors = ["Andrew Zody <zodyac@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
